for(var textIDPosition=2,cycleDivisions=36,plotRows=50,volumeTotal=Array(cycleDivisions+1),pressure=Array(cycleDivisions+1),averagePressureOneStep=Array(cycleDivisions+1),deltaVolume=Array(cycleDivisions+1),Pdv=Array(cycleDivisions+1),plotListX=Array(cycleDivisions),plotListY=Array(cycleDivisions),i=0;i<cycleDivisions;i++)plotListX[i]=0,plotListY[i]=0;for(var plotArray=Array(plotRows),k=0;k<plotRows;k++)plotArray[k]=Array(plotRows);
for(i=0;i<cycleDivisions+1;i++)volumeTotal[i]=1,pressure[i]=1,Pdv[i]=1;
var dataRow=[["title","Input Specification","Value","Units"],["input","Power cylinder diameter","powerCylDia"," mm"],["input","Power cylinder stroke","powerCylStroke"," mm"],["input"," Displacer diameter","displacerDia","mm"],["input"," Displacer stroke","displacerStroke","mm"],["input"," Dead volume (Hot)","deadVolHot","cm^3"],["input"," Dead volume (Cold)","deadVolCold","cm^3 "],["input"," Dead volume (Regenerator)","deadVolRegen","cm^3"],["input"," Engine cycles/sec","cyclesPerSec","Hz"],["input",
" Hot gas temperature","tHot","degC"],["input"," Cold gas Temperature","tCold"," degC"],["input"," Average Pressure","pressureAve"," Atm"],["input"," Gas Constant","gasConstant","kJ/kg-K"]],resultRow=[["title"," Results","Value","Units"],["result","Net Work (per cycle)","workNet","Joules"],["result","Work out","workExpansion","Joules"],["result","Work in","workCompression","Joules"],["result","Power = net Work x cycle/sec","power","watt"],["result"," Max Pressure","pressureMax"," Atm"],["result",
" Min Pressure","pressureMin"," Atm "],["result","Pressure ratio","pressureRatio",""],["result","Max volume","volumeMax","cm^3"],["result","Min volume","volumeMin","cm^3"],["result","Volume ratio","volumeRatio",""],["result","Mass of operating gas","massTotal","g"],["result","Temperature ratio","temperatureRatio",""],["result","Isentropic compression heating","compressionHeatIsentropic","%"]];
function setInitialValues(a){a.powerCylDia.value="50";a.powerCylStroke.value="50";a.displacerDia.value="50";a.displacerStroke.value="50";a.deadVolHot.value="0";a.deadVolCold.value="0";a.deadVolRegen.value="0";a.cyclesPerSec.value="1";a.tHot.value="100";a.tCold.value="24";a.pressureAve.value="1";a.gasConstant.value=".2870"}
var isoTEngine={setSpecifications:function(a){this.tHot=convertTemperature(parseFloat(a.tHot.value),"C");this.tCold=convertTemperature(parseFloat(a.tCold.value),"C");this.powerCylDia=parseFloat(a.powerCylDia.value)/1E3;this.powerCylStroke=parseFloat(a.powerCylStroke.value)/1E3;this.displacerDia=parseFloat(a.displacerDia.value)/1E3;this.displacerStroke=parseFloat(a.displacerStroke.value)/1E3;this.deadVolHot=parseFloat(a.deadVolHot.value)/1E6;this.deadVolCold=parseFloat(a.deadVolCold.value)/1E6;this.deadVolRegen=
parseFloat(a.deadVolRegen.value)/1E6;this.cyclesPerSec=parseFloat(a.cyclesPerSec.value);this.pressureAveGoal=101.325*parseFloat(a.pressureAve.value);this.gasConstant=parseFloat(a.gasConstant.value);this.phi=-Math.PI/2},tRegenCompute:function(){this.tRegen=(this.tHot-this.tCold)/Math.log(this.tHot/this.tCold)},powerCylVolMaxCompute:function(){this.powerCylVolMax=Math.PI*this.powerCylDia*this.powerCylDia*this.powerCylStroke/4},displacerHVolMaxCompute:function(){this.displacerHVolMax=Math.PI*this.displacerDia*
this.displacerDia*this.displacerStroke/4},powerCylVolCompute:function(a){this.powerCylVol=this.powerCylVolMax*(1+Math.cos(a+this.phi))/2},displacerHVolCompute:function(a){this.displacerHVol=this.displacerHVolMax*(1+Math.cos(a))/2;this.displacerCVol=this.displacerHVolMax-this.displacerHVol},coldVolCompute:function(){this.coldVol=this.displacerHVolMax-this.displacerHVol+this.deadVolCold+this.powerCylVol},hotVolCompute:function(){this.hotVol=this.displacerHVol+this.deadVolHot},totalVolCompute:function(a){this.powerCylVolCompute(a);
this.totalVol=this.displacerHVolMax+this.powerCylVol+this.deadVolRegen+this.deadVolCold+this.deadVolHot},massTotalCompute:function(a){this.massTotal=a/this.gasConstant*(this.coldVol/this.tCold+this.hotVol/this.tHot+this.deadVolRegen/this.tRegen)},pressureCompute:function(){this.pressure=this.massTotal*this.gasConstant/(this.coldVol/this.tCold+this.hotVol/this.tHot+this.deadVolRegen/this.tRegen)},volumeMaxCompute:function(){this.volumeMax=this.powerCylVolMax+this.displacerHVolMax+this.deadVolHot+this.deadVolCold+
this.deadVolRegen},volumeMinCompute:function(){this.volumeMin=this.displacerHVolMax+this.deadVolHot+this.deadVolCold+this.deadVolRegen},compressionHeatIsentropicCompute:function(){var a=this.volumeMax/this.volumeMin,a=Math.pow(a,0.4),a=(a-1)/(this.tHot/this.tCold-1);this.compressionHeatIsentropic=100*a},renewThetaCompute:function(a){isoTEngine.powerCylVolCompute(a);isoTEngine.displacerHVolCompute(a);isoTEngine.coldVolCompute();isoTEngine.hotVolCompute();isoTEngine.totalVolCompute(a)}};
function updateForm(){var a=document.getElementById("inputForm");updateCalc(a);updateOutput();updatePvPlot();updateTable()}
function updateCalc(a){isoTEngine.setSpecifications(a);isoTEngine.tRegenCompute();isoTEngine.powerCylVolMaxCompute();isoTEngine.powerCylVolCompute(0);isoTEngine.displacerHVolMaxCompute();isoTEngine.displacerHVolCompute(0);isoTEngine.coldVolCompute();isoTEngine.hotVolCompute();isoTEngine.totalVolCompute();pressureSeek(isoTEngine.pressureAveGoal);isoTEngine.volumeMaxCompute();isoTEngine.volumeMinCompute();isoTEngine.compressionHeatIsentropicCompute();isoTEngine.cyclesPerSec=a.cyclesPerSec.value}
function updateOutput(){document.getElementById("volumeMax").innerHTML=(1E6*isoTEngine.volumeMax).toPrecision(4);document.getElementById("volumeMin").innerHTML=(1E6*isoTEngine.volumeMin).toPrecision(4);document.getElementById("volumeRatio").innerHTML=(isoTEngine.volumeMax/isoTEngine.volumeMin).toPrecision(4);document.getElementById("compressionHeatIsentropic").innerHTML=isoTEngine.compressionHeatIsentropic.toPrecision(4);document.getElementById("workNet").innerHTML=isoTEngine.workNet;document.getElementById("workExpansion").innerHTML=
isoTEngine.workExpansion;document.getElementById("workCompression").innerHTML=isoTEngine.workCompression;document.getElementById("power").innerHTML=(isoTEngine.workNet*isoTEngine.cyclesPerSec).toPrecision(4);document.getElementById("massTotal").innerHTML=(1E3*isoTEngine.massTotal).toPrecision(4);document.getElementById("pressureMin").innerHTML=(isoTEngine.pressureMin/101.325).toPrecision(4);document.getElementById("pressureMax").innerHTML=(isoTEngine.pressureMax/101.325).toPrecision(4);document.getElementById("pressureRatio").innerHTML=
(isoTEngine.pressureMax/isoTEngine.pressureMin).toPrecision(4);document.getElementById("temperatureRatio").innerHTML=(isoTEngine.tHot/isoTEngine.tCold).toPrecision(4);document.getElementById("plotPressureMax").innerHTML=(isoTEngine.pressureMax/101.325).toPrecision(4);document.getElementById("plotPressureMin").innerHTML=(isoTEngine.pressureMin/101.325).toPrecision(4);document.getElementById("plotVmax").innerHTML=(1E6*isoTEngine.volumeMax).toPrecision(4);document.getElementById("plotVmin").innerHTML=
(1E6*isoTEngine.volumeMin).toPrecision(4)}
function pressureSeek(a){for(var b=0,c=0,e=0,f=0,g=0,h,j,d=0.011,l=0,p=0,m=0,n=0;0.001<Math.abs(d);){0==n?m=a/2:(m=1==n?a:(p-l)*(a-b)/(c-b)+l,p=l,c=b);l=m;n++;if(20<n)return b;g=f=e=b=0;j=h=a;isoTEngine.renewThetaCompute(Math.PI);isoTEngine.massTotalCompute(m);for(d=0;d<cycleDivisions+1;d++)isoTEngine.renewThetaCompute(2*d/cycleDivisions*Math.PI),isoTEngine.pressureCompute(),volumeTotal[d]=isoTEngine.totalVol,pressure[d]=isoTEngine.pressure,0<d&&(b+=isoTEngine.pressure,averagePressureOneStep[d-1]=
(pressure[d-1]+pressure[d])/2,deltaVolume[d-1]=volumeTotal[d]-volumeTotal[d-1],isoTEngine.pressure<h&&(h=isoTEngine.pressure),isoTEngine.pressure>j&&(j=isoTEngine.pressure));b/=cycleDivisions;d=a-b;isoTEngine.pressureMin=h;isoTEngine.pressureMax=j}for(d=0;d<cycleDivisions;d++)a=(averagePressureOneStep[d]-b)*deltaVolume[d],Pdv[d]=(1E3*a).toPrecision(4),e+=a,0<=a&&(g+=a),0>a&&(f+=a),volumeTotal[d]=(1E6*volumeTotal[d]).toPrecision(4),pressure[d]=(pressure[d]/101.325).toPrecision(4),averagePressureOneStep[d]=
(averagePressureOneStep[d]/101.325).toPrecision(4),deltaVolume[d]=(1E6*deltaVolume[d]).toPrecision(4);isoTEngine.workNet=(1E3*e).toPrecision(4);isoTEngine.workExpansion=(1E3*g).toPrecision(4);isoTEngine.workCompression=(1E3*f).toPrecision(4);return b}function convertTemperature(a,b){var c=0;"K"==b?c=a:"C"==b?c=a+273.15:"R"==b?c=5*a/9:"F"==b?c=5*(a+459.67)/9:alert("temperature scale error");return c}function tempRatioDegC(a,b){return((parseFloat(a)+273)/(parseFloat(b)+273)).toPrecision(4)}
function makePvPlot(){for(var a=0;a<plotRows;a++){for(var b="<tr height='4'>",c=0;c<plotRows;c++)b+="<td align center id=pvPlot"+c+"y"+a+" ><img src='/img/white.gif' id = 'white' width='4' cellspacing='0'  valign='center'></td>";b+="</tr>";document.write(b)}}
function updatePvPlot(){for(var a=0;a<cycleDivisions;a++)document.getElementById("pvPlot"+plotListX[a]+"y"+plotListY[a]).innerHTML="<img src='/img/white.gif'  id = 'white' >";for(var b=isoTEngine.pressureMin/101.325,c=isoTEngine.pressureMax/101.325,e=1E6*isoTEngine.volumeMax,f=1E6*isoTEngine.volumeMin,a=0;a<cycleDivisions;a++){var g=Math.round((volumeTotal[a]-f)*(plotRows-1)/(e-f)),h=Math.round((pressure[a]-b)*(plotRows-1)/(c-b));plotArray[g][plotRows-h-1]=!0;plotListX[a]=g;plotListY[a]=plotRows-
h-1;document.getElementById("pvPlot"+plotListX[a]+"y"+plotListY[a]).innerHTML="<img src='/img/black.gif'  id = 'black' >"}}var columnHeads=["Crankshaft angle"," Total volume"," Pressure"," Pdv "],columnUnits=["degrees"," cm^3"," Atm"," Joules"],columnWidths=["30","30","30","30"];
function generateTable(a,b){document.write("<br>");document.write("<table border='1' cellpadding='2' cellspacing='1' bgcolor=#dddddd id='table2'>");document.write(makeTitleRow());document.write(makeUnitsRow());for(var c=a;c<b;c++)document.write(makeOneRow(c));document.write("</table>")}
function updateTable(){for(var a=0;a<cycleDivisions;a++)document.getElementById("volume"+a).innerHTML=volumeTotal[a],document.getElementById("pressure"+a).innerHTML=pressure[a],document.getElementById("Pdv"+a).innerHTML=Pdv[a]}
function makeOneRow(a){a="<tr align='center'>"+("<td align=middle >"+360*a/cycleDivisions+"</td><td align='center' id=volume"+a+">"+volumeTotal[a]+"</td><td align='center' id=pressure"+a+">"+pressure[a]+"</td><td align='center' id=Pdv"+a+">"+Pdv[a]+"</td>");return a+"</tr>"}function makeTitleRow(){for(var a="<tr align='center' >",b=0;b<columnHeads.length;b++)a+="<th width="+columnWidths[b]+"align='center' >"+columnHeads[b]+"</th>";return a+"</tr>"}
function makeUnitsRow(){for(var a="<tr align='center'>",b=0;b<columnUnits.length;b++)a+="<th width="+columnWidths[b]+"align='center' >"+columnUnits[b]+"</th>";return a+"</tr>"}function makeInputTable(){for(var a=0;a<dataRow.length;a++)document.write("<tr>"+makeDataRow(dataRow[a],2)+"</tr>")}function makeResultTable(){for(var a=0;a<resultRow.length;a++)document.write("<tr>"+makeDataRow(resultRow[a],2)+"</tr>")}
function makeDataRow(a,b){var c="";if("title"==a[0]){for(var c="",e=1;e<a.length;e++)c+="<th bgcolor=#99ddff >"+a[e]+"</th>";return c}if("result"==a[0])for(e=1;e<a.length;e++)c=e==b&&""!=a[e]?c+("<td align='left' width='70' id="+a[e]+"></td>"):c+("<td align=left>"+a[e]+"</td>");else if("input"==a[0])for(e=1;e<a.length;e++)c=e==b&&""!=a[e]?c+("<td align=left ><input type=text size=8 onchange=updateForm(getElementById('inputForm')) id="+a[e]+" value="+a[e]+" ></td>"):c+("<td align=left>"+a[e]+"</td>");
return c}
function calculator(){document.write("<table border='0' cellpadding='2' cellspacing='1' bgcolor=#dddddd id='layoutTable' >");document.write("<tr> <td valign='top'>");document.write("<table  border='1' cellpadding='2' cellspacing='0' id='inputTable'>");makeInputTable();document.write("</table>");document.write("</td> <td valign='top' >");document.write("<table border='1' cellpadding='2' cellspacing='0' id='resultTable'>");makeResultTable();document.write("</table>");document.write("</td></tr>");document.write("<tr > <th  align='right' valign='top' id='plotPressureMax'>");
document.write("</th> <td  rowspan=3>");document.write("<table border='0' cellpadding='1' bgcolor=#FFFFFF cellspacing ='0' style='font-size: 0;' id='pvPlot' >");makePvPlot();document.write("</table>");document.write("</td></tr>");document.write("<tr> <th align='right' valign='center'> pressure Atm");document.write("</th></tr>");document.write("<tr> <th align='right' valign='bottom' id='plotPressureMin'>");document.write("</th></tr>");document.write("<tr> <td align='center' valign='top'>");document.write("</td> <td > ");
document.write("<table border='0' cellpadding='1' cellspacing = '0' id='pvPlotCaption'>");document.write("<tr valign='top'> <th align='left' width='30%' id='plotVmin'>");document.write("</th> <td >");document.write("</td> <th align ='center' width='40%'> Volume cm^3");document.write("</th> <td >");document.write("</td> <th align ='right' width='30%' id='plotVmax'>");document.write("</th></tr>");document.write("</table>");document.write("</td></tr>");document.write("</td></tr>");document.write("</td></tr>");
document.write("<tr> <td align='center' width ='315' valign='top' border='1'>");generateTable(0,18);document.write("</td> <td align ='center' width ='315' valign='top' border='1'>");generateTable(18,cycleDivisions);document.write("</td></tr>");document.write("</table>");setInitialValues(document.getElementById("inputForm"));updateForm()};